### ISSUE TITLE
Accessiblity Issue

### ISSUE THREAD

**Issue by Rahulbaran** [Moamal-2000/template2#10]
Hey Moamal,
There are some accessibility issues in your html code where I might help.

**Comment by Rahulbaran** [comment]
You should convert all the images in `webp` form which will significantly enhance your site performace.
Also there are some accessbility issues in your **HTML Code**, which I can remove if you want.

**Comment by Moamal-2000** [comment]
> You should convert all the images in `webp` form which will significantly enhance your site performance. Also there are some accessbility issues in your **HTML Code**, which I can remove if you want.

would be nice bro, and thanks for this advice I will convert them to webp if that is possible
